import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from dotenv import load_dotenv

load_dotenv(override=True)

def send_email_with_attachment(recipient_email: str, pdf_filename: str):
    sender_email = os.getenv("SMTP_SENDER_EMAIL")
    sender_password = os.getenv("SMTP_SENDER_PASSWORD")
    
    if not sender_email or not sender_password:
        return False, "Missing SMTP credentials in .env file."

    try:
        msg = MIMEMultipart()
        msg['From'] = f"AI Analytics Agent <{sender_email}>"
        msg['To'] = recipient_email
        msg['Subject'] = "🚨 Anomaly Detection Alert & Analytics Report"

        body = "Hello,\n\nPlease find attached the latest Anomaly Detection Report generated by AI Analytics Agent.\n\nBest regards,\nAI Analytics Agent Team"
        msg.attach(MIMEText(body, 'plain'))

        if os.path.exists(pdf_filename):
            with open(pdf_filename, "rb") as f:
                attach = MIMEApplication(f.read(), _subtype="pdf")
                attach.add_header('Content-Disposition', 'attachment', filename=os.path.basename(pdf_filename))
                msg.attach(attach)

        # Port 587 (TLS) Working Implementation
        server = smtplib.SMTP('smtp.gmail.com', 587, timeout=15)
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(sender_email, sender_password.replace(" ", "").strip())
        server.send_message(msg)
        server.quit()

        return True, "Email sent successfully!"

    except Exception as e:
        return False, f"SMTP Error: {str(e)}"